version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  user_app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy